// Source selection is a frontend contract. No filesystem or network discovery occurs here.
const sourceFields=document.createElement('div');sourceFields.className='card source-fields';sourceFields.innerHTML='<h2>從哪裡取得產品資料？</h2><label class="field"><span>資料查找方式</span><select id="sourceMode"><option value="catalog">產品＋版本查找</option><option value="path">指定資料路徑</option><option value="manual">手動提供情境／檔案／CVE</option></select></label><label class="field" id="sourcePathField"><span>工程資料根目錄或儲存位置</span><input id="sourcePath" maxlength="1000" placeholder="例如：/srv/releases/EG210/2.8.1/ 或 C:\\Engineering\\EG210\\2.8.1"><small>只記錄位置。此公開預覽無法讀取你電腦、共享磁碟或伺服器上的路徑。</small></label><p class="muted" id="sourceHelp"></p>';
$('requestForm').prepend(sourceFields);
document.querySelector('#requestForm button[type="submit"]').textContent='下一步：查找與確認資料 →';
const sourceFill=fillDraft;fillDraft=function(){sourceFill();$('sourceMode').value=product().sourceMode||'catalog';$('sourcePath').value=product().sourcePath||'';sourceHint()};
function sourceHint(){const mode=$('sourceMode').value;$('sourcePathField').classList.toggle('hidden',mode!=='path');$('sourceHelp').textContent=mode==='catalog'?'依下方產品名稱與版本，向產品資料庫查找 SBOM、建置與產物資料。此版展示查找結果樣例。':mode==='path'?'從指定位置尋找相關工程資料，再確認產品與建置是否一致。此版不會掃描真實路徑。':'提供已掌握的資訊即可；缺少的材料會在下一步整理。'}
function saveSource(){const p=product();p.sourceMode=$('sourceMode').value;p.sourcePath=$('sourcePath').value.trim();p.mode='draft';p.runId=null;p.sourceReview=null;sourceHint();render()}
$('sourceMode').onchange=saveSource;$('sourcePath').oninput=saveSource;
const sourcePage=document.createElement('section');sourcePage.id='collection';sourcePage.className='view';sourcePage.innerHTML='<article class="card"><div class="eyebrow">SOURCE → MATERIAL → GAP</div><h2>確認找到的資料與待補項目</h2><p id="sourceSummary"></p><div class="note" style="margin:18px 0">查找結果樣例 · 資料連接器尚未接入，以下不表示實際讀取或驗證成功。</div><div id="sourceRows"></div><p class="muted" style="margin:18px 0">資料可不完整，但未知條件需保留。資料齊全也不代表不受影響，仍須執行 Query 與工程覆核。</p><div class="buttonrow"><button class="btn primary" id="sourceContinue">下一步：確認缺件與 AI 建議 →</button><button class="btn" id="sourceEdit">修改來源</button></div></article>';
document.querySelector('footer').before(sourcePage);
const sourceNav=document.createElement('button');sourceNav.dataset.view='collection';document.querySelector('.nav').append(sourceNav);
const navLayout=[['intake','01 產品與資料來源'],['collection','02 資料確認與缺件'],['overview','03 分析進度與結果'],['report','04 報告與後續行動'],['advice','✧ AI 建議與追問'],['evidence','↗ 證據瀏覽器'],['supplement','↻ 補件與版本歷程']];
navLayout.forEach(([id,label])=>{const b=document.querySelector('[data-view="'+id+'"]');b.textContent=label;document.querySelector('.nav').append(b);b.onclick=()=>go(id)});
const toolsLabel=document.createElement('div');toolsLabel.className='navlabel';toolsLabel.style.margin='18px 12px 8px';toolsLabel.textContent='查核工具 · 可反覆使用';document.querySelector('[data-view="advice"]').before(toolsLabel);
const sourceAccess=accessFor;accessFor=function(view){if(view==='collection')return product().mode==='draft'?'先選定產品與資料來源':'';return sourceAccess(view)};
function drawSources(){const p=product();$('sourceSummary').textContent=p.name+' / '+(p.release||'版本待確認')+' · '+(p.sourceMode==='path'?'位置：'+p.sourcePath:p.sourceMode==='manual'?'手動提供資訊':'產品與版本索引');$('sourceRows').replaceChildren();const automatic=p.sourceMode!=='manual';const complete=p.mode==='sample'&&(current!=='C'||supplemented);const rows=[['元件／SBOM','PC1 · Q1','SBOM、版本、來源清單',automatic],['建置／修補／實作','PC2 · Q2、Q3','build log、有效旗標、修補紀錄、symbols',false],['產物與使用路徑','PC3 · Q4、Q5','同次建置 manifest、hash、consumer 設定與正常觀測',false]];rows.forEach(([name,pc,needed,found])=>{const card=document.createElement('div');card.className='source-row';const main=document.createElement('div');const h=document.createElement('h3');h.textContent=name;const desc=document.createElement('p');desc.textContent=pc+' · '+needed;main.append(h,desc);const badge=document.createElement('span');badge.className='pill '+(complete||found?'':'amber');badge.textContent=complete?'示例：已補入，待覆核':found?'示例：找到候選，待核對':'待補／待確認';card.append(main,badge);$('sourceRows').append(card)});if(p.files.length){const note=document.createElement('p');note.textContent='已選檔案（僅檔名，尚未讀取）：'+p.files.map(f=>f.name).join('、');$('sourceRows').append(note)}}
const sourceGo=go;go=function(view){if(view==='collection'){const reason=accessFor(view);if(reason){toast(reason);return}currentView=view;document.querySelectorAll('.view').forEach(el=>el.classList.toggle('active',el.id===view));document.querySelectorAll('.nav button').forEach(b=>{b.classList.toggle('active',b.dataset.view===view);if(b.dataset.view===view)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')});$('shell').classList.remove('page-intake');$('title').textContent='資料確認與缺件';$('subtitle').textContent='先確認來源與建置範圍，再決定需要補什麼。';$('crumb').textContent='資料確認';drawSources();window.scrollTo({top:0,behavior:'smooth'});return}sourceGo(view);if(currentView==='intake'){$('title').textContent='產品與資料來源';$('subtitle').textContent='先選產品與版本或指定路徑，讓系統整理可用材料。'}if(currentView==='report'){$('title').textContent='報告與後續行動';$('subtitle').textContent='報告保留未知與缺口，補件後建立新的分析紀錄。'}};
$('requestForm').onsubmit=e=>{e.preventDefault();saveDraft();const p=product();p.sourceMode=$('sourceMode').value;p.sourcePath=$('sourcePath').value.trim();const ids=p.cve.toUpperCase().split(/[\s,，;；]+/).filter(Boolean);let error='';if(p.sourceMode==='catalog'&&(!p.name.trim()||!p.release.trim()))error='請提供產品名稱與版本，才能查找對應材料。';if(p.sourceMode==='path'&&!p.sourcePath)error='請提供要查找的資料位置。';if(p.sourceMode==='manual'&&!p.description.trim()&&!p.cve.trim()&&!p.files.length)error='請提供情境、檔案或 CVE 至少一項。';if(ids.some(id=>!/^CVE-\d{4}-\d{4,}$/.test(id)))error='請使用 CVE-年份-編號格式。';if(error){$('requestError').textContent=error;$('requestError').classList.remove('hidden');return}p.cve=[...new Set(ids)].join(', ');p.mode='plan';p.runId='PLAN-'+crypto.randomUUID().slice(0,8);p.startedAt=new Date().toISOString();render();go('collection')};
$('sourceContinue').onclick=()=>go('advice');$('sourceEdit').onclick=()=>go('intake');
const reportFollowup=document.createElement('article');reportFollowup.className='card';reportFollowup.innerHTML='<h2>報告後，繼續完成查核</h2><p>依本次證據與未知條件整理補件方向；新資料需對應相同產品與建置，再建立新的分析紀錄。</p><div class="buttonrow" style="margin-top:16px"><button class="btn primary" id="reportAdvice">查看建議與待確認問題 →</button><button class="btn" id="reportSupplement">補件與重新分析 →</button></div><p class="muted" id="reportFollowupHint"></p>';$('report').append(reportFollowup);$('reportAdvice').onclick=()=>go('advice');$('reportSupplement').onclick=()=>go('supplement');
const sourceRender=render;render=function(){sourceRender();drawSources();$('reportSupplement').disabled=!!accessFor('supplement');$('reportFollowupHint').textContent=product().mode==='sample'&&current==='C'?'保留舊報告與分析紀錄，從補件歷程查看更新。':'目前沒有已確認缺件；可先查看建議與待確認問題。';navState.textContent=product().mode==='draft'?'先選產品與資料來源，再確認候選材料與缺件。':product().mode==='plan'?'來源已記錄。確認材料 → AI 建議 → 模擬分析；真實查找尚未接入。':'示例結果已開放。報告可回到建議與補件，保留分析歷程。'};
document.querySelector('#scenarioInput + small').textContent='選填。補充產品用途、掃描告警或本次想確認的問題。';
const sourceAccessFinal=accessFor;accessFor=function(view){if(product().mode==='draft'&&view!=='intake')return '先選定產品與資料來源，完成資料確認';return sourceAccessFinal(view)};
fillDraft();render();go('intake');
