// State-aware product navigation. Advice is local preparation, never analysis evidence.
const adviceNav=document.createElement('button');adviceNav.dataset.view='advice';adviceNav.textContent='✧ AI 查核建議';document.querySelector('[data-view="evidence"]').before(adviceNav);
const navState=document.createElement('p');navState.className='nav-state';navState.setAttribute('aria-live','polite');document.querySelector('.nav').after(navState);
const advicePage=document.createElement('section');advicePage.id='advice';advicePage.className='view';advicePage.innerHTML='<div class="advice-context" id="adviceContext"></div><div class="advice-layout"><div><div class="note" style="margin-bottom:20px">建議示例 · AI 尚未連線。以下為資料準備範本，不代表已查出缺件或完成漏洞判定。</div><div id="adviceCards"></div></div><aside class="card advice-sidebar"><div class="eyebrow">NEXT BEST ACTION</div><h2>讓未知有下一步</h2><p id="adviceCount"></p><ol><li>確認本次產品與版本</li><li>依問題準備原始資料</li><li>核對是否為同次建置</li><li>查核證據，再覆核結論</li></ol><p class="muted">補充說明只儲存在本頁記憶體，不會上傳，也不會改變 PC 判定。重新整理即清除。</p><button class="btn" id="exportAdvice">下載資料準備清單</button><button class="textbtn" id="adviceToInput" style="margin-top:16px">返回產品輸入 →</button></aside></div>';
document.querySelector('footer').before(advicePage);
const nextAction=document.createElement('div');nextAction.className='next-action';nextAction.innerHTML='<div><b id="nextTitle"></b><p id="nextDetail"></p></div><button class="btn primary" id="nextAdvice">查看資料建議 →</button>';$('overview').prepend(nextAction);
function accessFor(view){const p=product();if(view==='intake')return '';if(p.mode==='draft')return '先提供情境、檔案或 CVE，並開始查核';if(view==='overview'||view==='advice')return '';if(p.mode!=='sample')return '分析結果尚未產生，請先查看資料準備建議';if(view==='supplement'&&current!=='C')return '目前示例沒有待補件；可切換至缺件情境';return ''}
const uxGo=go;go=function(view){const reason=accessFor(view);if(reason){toast(reason);return}if(view==='advice'){currentView=view;document.querySelectorAll('.view').forEach(el=>el.classList.toggle('active',el.id===view));document.querySelectorAll('.nav button').forEach(el=>el.classList.toggle('active',el.dataset.view===view));$('shell').classList.remove('page-intake');$('title').textContent='AI 查核建議';$('subtitle').textContent='把待確認的問題，轉成可以準備的產品資料。';$('crumb').textContent='AI 查核建議';renderAdvice();window.scrollTo({top:0,behavior:'smooth'})}else uxGo(view);document.querySelectorAll('.nav button').forEach(b=>{if(b.dataset.view===view)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')})};
function adviceItems(){const p=product();const cve=p.activeCve||p.cve;const detail=cve==='CVE-2014-0160'?'OpenSSL 版本、heartbeat 編譯設定與 TLS 入口':cve==='CVE-2022-37434'?'zlib 版本、修正紀錄與 gzip 解壓縮呼叫':cve==='CVE-2023-38545'?'curl 版本、修補紀錄與 SOCKS5 hostname 設定':'目標元件、實際編譯設定與產品使用入口';return [
{pc:'PC1',query:'Q1_COMPONENT',title:'產品實際包含哪個元件與版本？',provide:'SBOM、套件版本、供應商版本資訊或元件來源；請標示產品型號與 Release。',why:'先對齊元件身分與來源，避免僅憑掃描名稱推定命中。'},
{pc:'PC2',query:'Q2_BUILD · Q3_IMPLEMENTATION',title:'受影響功能有被編入，或已經修補嗎？',provide:'同次建置的 build log、有效編譯旗標、修補紀錄、原始碼片段或 symbols。',why:'需要核對 '+detail+'。資料仍須依目標 CVE 的完整條件查證。'},
{pc:'PC3',query:'Q4_BINDING · Q5_PATH',title:'出貨產品如何使用這段程式？',provide:'產物 manifest／hash、link map、consumer source、啟動設定與正常執行觀測。',why:'將來源、library 與出貨成品連起來，確認產品入口及必要使用條件。'}]}
function adviceStore(){const p=product();p.adviceNotes??={};const key=[p.release,p.activeCve||'unresolved',p.runId||'draft',p.mode==='sample'?current:''].join('|');return p.adviceNotes[key]??=(['','',''])}
function updateAdviceCount(){const notes=adviceStore();$('adviceCount').textContent=notes.filter(x=>x.trim()).length+' / 3 項已記錄說明 · 尚未查證'}
function renderAdvice(){const p=product();$('adviceContext').replaceChildren();[p.name,p.release||'Release 未指定',p.activeCve||'CVE 待確認'].forEach(t=>{const s=document.createElement('span');s.className='pill';s.textContent=t;$('adviceContext').append(s)});$('adviceCards').replaceChildren();const notes=adviceStore();adviceItems().forEach((item,i)=>{const card=document.createElement('article');card.className='card advice-card';card.innerHTML='<div class="advice-head"><span class="pill"></span><span class="source-mini"></span></div><h2></h2><dl><dt>建議提供</dt><dd></dd><dt>為什麼需要</dt><dd></dd></dl><label class="field"><span>我的補充說明</span><textarea maxlength="2000" placeholder="例如：由韌體同事提供本次 Release 的編譯紀錄；尚待確認 build ID。"></textarea></label><div class="advice-status" aria-live="polite"></div>';
card.querySelector('.pill').textContent=item.pc;card.querySelector('.source-mini').textContent=item.query;card.querySelector('h2').textContent=(i+1)+'. '+item.title;const dd=card.querySelectorAll('dd');dd[0].textContent=item.provide;dd[1].textContent=item.why;const input=card.querySelector('textarea');input.value=notes[i];const status=card.querySelector('.advice-status');status.textContent=notes[i].trim()?'已記錄說明 · 待查證':'尚未提供說明';input.oninput=()=>{notes[i]=input.value;status.textContent=input.value.trim()?'已記錄說明 · 待查證':'尚未提供說明';updateAdviceCount()};$('adviceCards').append(card)});updateAdviceCount()}
const uxRender=render;render=function(){uxRender();const p=product();document.querySelectorAll('.nav button').forEach(b=>{const reason=accessFor(b.dataset.view);b.disabled=!!reason;b.setAttribute('aria-disabled',String(!!reason));b.title=reason||b.textContent});navState.textContent=p.mode==='draft'?'① 建立查核後，開啟分析進度與資料建議。其餘入口於結果產生後開放。':p.mode==='plan'?'② 輸入已整理，尚未分析。可先準備資料；證據、補件與報告等待結果。':'③ 正在瀏覽示例結果。AI 建議提供資料方向，結論仍需工程師覆核。';$('downloadReport').disabled=p.mode!=='sample';$('nextTitle').textContent=p.mode==='sample'?'下一步：核對證據，釐清待確認事項':'輸入已整理，先準備查核所需資料';$('nextDetail').textContent=p.mode==='sample'?'從三個問題整理產品資料與團隊待辦。':'分析服務尚未接入；目前不會自動產生結果。';$('planNotice').textContent=p.mode==='sample'?'示例資料 · 可查看查詢、證據與補件結果。':'輸入已整理 · 尚未提交至分析服務。';$('aiAction').textContent='查看 AI 查核建議 →';$('aiAction').onclick=()=>go('advice');renderAdvice();if(accessFor(currentView))go(p.mode==='draft'?'intake':'overview')};
document.querySelectorAll('.nav button').forEach(b=>b.onclick=()=>go(b.dataset.view));$('nextAdvice').onclick=()=>go('advice');$('adviceToInput').onclick=()=>go('intake');
$('exportAdvice').onclick=()=>{const p=product();const notes=adviceStore();download('CVEvidence-material-checklist.txt',['資料準備建議示例（AI 尚未連線，未完成查證）',p.name,p.release,p.activeCve||'CVE 待確認',...adviceItems().map((a,i)=>'\n'+a.pc+' / '+a.query+'\n'+a.title+'\n建議提供：'+a.provide+'\n原因：'+a.why+'\n補充說明：'+(notes[i]||'未提供'))].join('\n'))};
const exampleBefore=$('exampleInput').onclick;$('exampleInput').onclick=()=>{exampleBefore();product().mode='draft';product().runId=null;render()};
const adviceNext=document.createElement('div');adviceNext.className='advice-next';adviceNext.innerHTML='<h3>繼續查核流程</h3><p id="adviceNextHint"></p><label class="field" id="nextSampleField"><span>模擬資料組</span><select id="nextSampleFamily"><option value="firmware">Firmware · OpenSSL</option><option value="cmake">CMake · zlib</option><option value="curl">curl · SOCKS5</option></select></label><button class="btn primary" id="adviceContinue">下一步：查看模擬分析 →</button>';$('exportAdvice').before(adviceNext);
const adviceNextRender=renderAdvice;renderAdvice=function(){adviceNextRender();const p=product();const sample=p.mode==='sample';$('nextSampleField').classList.toggle('hidden',sample);$('adviceContinue').textContent=sample?(current==='C'&&!supplemented?'下一步：補齊示例資料 →':'下一步：查看查核證據 →'):'下一步：查看模擬分析 →';$('adviceNextHint').textContent=sample?'繼續本示例的查核流程；補充說明不會直接改變判定。':'後端尚未接入。下一步另建「證據不足」示例產品，保留你的輸入與說明，不會分析或上傳你的資料。';$('nextSampleFamily').value=p.activeCve==='CVE-2022-37434'?'cmake':p.activeCve==='CVE-2023-38545'?'curl':'firmware'};
$('adviceContinue').onclick=()=>{if(product().mode==='sample'){go(current==='C'&&!supplemented?'supplement':'evidence');return}const f=$('nextSampleFamily').value;snapshot();const p=newProduct(families[f].label+' · 模擬查核');p.family=f;p.mode='sample';p.scenario='C';p.cve=families[f].cve.split(' · ')[0];p.description='獨立的證據不足示例；不代表使用者輸入產品的實際分析。';p.runId='SAMPLE-'+crypto.randomUUID().slice(0,8);products.push(p);activeProduct=p.id;family=f;current='C';supplemented=false;selectedEvidence=0;document.querySelectorAll('#report input[type="checkbox"]').forEach(c=>c.checked=false);render();go('overview');toast('已開啟獨立模擬結果。原產品輸入與補充說明保留，可從產品選單切回。')};
document.querySelector('.advice-sidebar').prepend(adviceNext);
render();go('intake');
