// Frontend-only requests. User-provided text is rendered via textContent, never HTML.
const DEMO_DATE='2026-09-12';
const queryDefinitions=[
 {id:'Q1_COMPONENT',pc:'PC1',name:'元件、版本與來源',purpose:'這個產品含有哪些元件？版本、來源與目標 CVE 是否對得上？',inputs:'SBOM、版本資訊、元件來源',outputs:'元件識別、版本事實、來源引用',evidence:0},
 {id:'Q2_BUILD',pc:'PC2',name:'建置、旗標與修補',purpose:'實際編譯了哪些功能？是否使用停用旗標、升級或 backport 修補？',inputs:'編譯命令、build log、修補收據',outputs:'有效旗標、修補紀錄、建置證據',evidence:1},
 {id:'Q3_IMPLEMENTATION',pc:'PC2',name:'受影響實作',purpose:'相關程式碼是否存在、被編入，或已有對應修正？',inputs:'原始碼、symbols、ELF 與修正片段',outputs:'實作位置、修正證據、觀察限制',evidence:1},
 {id:'Q4_BINDING',pc:'PC3',name:'產品與建置關聯',purpose:'來源、library、出貨產物與觀測，是否屬於同個產品建置？',inputs:'manifest、hash、link map、載入物件',outputs:'產物關聯、同版檢查、缺失連結',evidence:2},
 {id:'Q5_PATH',pc:'PC3',name:'產品使用路徑',purpose:'產品入口、設定與正常觀測，如何連到漏洞的必要使用條件？',inputs:'consumer source、啟動設定、執行觀測',outputs:'使用路徑、條件事實、待補證據',evidence:2}
];
const products=[newProduct('產品 01')];let activeProduct=products[0].id;
function newProduct(name){return {id:'P-'+crypto.randomUUID().slice(0,8),name,release:'demo-'+DEMO_DATE,description:'',cve:'',files:[],family:'firmware',scenario:'A',supplemented:false,mode:'draft',runId:null,startedAt:null}}
function product(){return products.find(p=>p.id===activeProduct)}
const previousGo=go,previousRender=render,previousEvidence=showEvidence;
const productbar=document.createElement('div');productbar.className='productstrip';productbar.innerHTML='<b>產品工作區</b><select id="productSelect" aria-label="目前產品"></select><button class="btn small" id="addProduct">＋ 新增產品</button><span class="spacer"></span><span class="modebadge" id="modeBadge">尚未建立分析</span><button class="textbtn" id="editRequest">編輯輸入 →</button>';
document.querySelector('.titlebar').before(productbar);
const intake=document.createElement('section');intake.id='intake';intake.className='view';intake.innerHTML=`<div class="grid"><article class="card"><div class="eyebrow">START WITH WHAT YOU KNOW</div><h2>描述情境、提供檔案，或直接輸入 CVE。</h2><p class="muted">不用先準備所有資料。先定義查核目標，再沿著五個 Query 找到證據與缺口。</p><div class="inputtabs"><span>情境描述</span><span>工程資料</span><span>CVE ID</span></div><form id="requestForm"><div class="form-row"><label class="field"><span>產品名稱</span><input id="productName" maxlength="80" required placeholder="例如：邊緣閘道器 GW-01"></label><label class="field"><span>版本／Release</span><input id="productRelease" maxlength="80" placeholder="例如：release-2026-09-12"></label></div><label class="field"><span>你想查核什麼？</span><textarea id="scenarioInput" maxlength="4000" placeholder="例如：這台閘道器使用 OpenSSL 處理 TLS，掃描報告提到 Heartbleed。我想確認目前出貨版本是否真的使用受影響功能，以及還缺哪些建置資料。"></textarea><small>情境、檔案或 CVE 至少提供一項。此版會整理輸入並展示分析計畫，不會用描述直接判定安全。</small></label><label class="field"><span>CVE ID（選填，可多筆）</span><input id="cveInput" maxlength="500" placeholder="CVE-2014-0160，或多個 CVE 以逗號分隔"><small>只知道 CVE 也可以先建立查核計畫。正式 CVE 知識查詢留待後端串接。</small></label><label class="field droparea"><span>選擇工程資料（選填，可多檔）</span><small>SBOM、ROM、原始碼包、ELF、build log、設定或分析報告。</small><input type="file" id="requestFiles" multiple><small>此預覽僅讀取檔名與大小，不讀取內容、不上傳。大型工程包後續由後端受控匯入。</small></label><div id="chosenFiles" class="filelist"></div><div id="requestError" class="inlineerror hidden" role="alert"></div><div class="buttonrow"><button type="submit" class="btn primary">建立分析鏈（模擬） →</button><button type="button" class="btn" id="exampleInput">填入情境範例</button></div></form></article><div><article class="card ai"><div class="eyebrow">HOW IT WILL WORK</div><h2>從需求到證據的分析鏈</h2><p>輸入整理 → CVE 與範圍釐清 → Q1–Q5 查證 → PC1–PC3 彙整 → 工程初判 → 補件與交接。</p><div class="querycallout"><b>PC1 · 元件與版本</b><p><code>Q1_COMPONENT</code></p></div><div class="querycallout"><b>PC2 · 建置與實作</b><p><code>Q2_BUILD + Q3_IMPLEMENTATION</code></p></div><div class="querycallout"><b>PC3 · 產品關聯與路徑</b><p><code>Q4_BINDING + Q5_PATH</code></p></div><p class="source-mini" style="margin-top:16px">這是前端預設分組；實際規則可跨 Query 引用事實。各 CVE 的條件由後端契約定義。</p></article><article class="card"><h2>想先看完整結果的形式？</h2><p class="muted">載入 3×3 合成情境，審核判斷、證據、補件及報告的預計呈現。</p><label class="field"><span>參考交付形式</span><select id="sampleFamily"><option value="firmware">Firmware ROM · OpenSSL</option><option value="cmake">CMake · zlib</option><option value="curl">curl 安裝包</option></select></label><button class="btn dark" id="loadSample">查看參考情境（合成結果）</button><p class="source-mini" style="margin-top:13px">會建立獨立示例產品，不會把合成結果套在你輸入的產品上。</p></article></div></div>`;
document.querySelector('footer').before(intake);
const newNav=document.createElement('button');newNav.dataset.view='intake';newNav.innerHTML='<span class="num">00</span>建立分析';document.querySelector('.nav').prepend(newNav);newNav.onclick=()=>go('intake');
const chainPanel=document.createElement('article');chainPanel.id='chainPanel';chainPanel.className='card';chainPanel.innerHTML='<div class="cardhead"><div><div class="eyebrow">TRACEABLE ANALYSIS CHAIN</div><h2>本次分析鏈</h2></div><span class="pill" id="chainRun"></span></div><div class="chain" id="chainSteps"></div><div class="chain-summary"><div><h3>查核目標</h3><div id="requestSummary" class="requesttext"></div></div><div><h3>輸入材料</h3><div id="materialSummary" class="requesttext"></div></div></div><div class="planbanner" id="planNotice" style="margin-top:18px;margin-bottom:0"></div>';
$('overview').prepend(chainPanel);
const queriesPanel=document.createElement('article');queriesPanel.className='card';queriesPanel.id='queriesPanel';queriesPanel.innerHTML='<div class="cardhead"><div><div class="eyebrow">QUERY → EVIDENCE → CONDITION</div><h2>五個分析 Query</h2></div><span class="pill">每個查詢保留來源與缺口</span></div><p class="muted" style="margin-bottom:20px">點開查詢計畫，查看需要哪些輸入、預期回傳什麼，以及如何支持 PC 條件。</p><div class="querygrid" id="queryCards"></div>';
$('overview').append(queriesPanel);
function saveDraft(){const p=product();const changed=p.name!==($('productName').value.trim()||'未命名產品')||p.release!==$('productRelease').value.trim()||p.description!==$('scenarioInput').value||p.cve!==$('cveInput').value;if(changed){p.mode='draft';p.runId=null}p.name=$('productName').value.trim()||'未命名產品';p.release=$('productRelease').value.trim();p.description=$('scenarioInput').value;p.cve=$('cveInput').value;refreshProducts();if(changed)render()}
function refreshProducts(){const select=$('productSelect');select.replaceChildren();products.forEach(p=>{const o=document.createElement('option');o.value=p.id;o.textContent=p.name;select.append(o)});select.value=activeProduct}
function fillDraft(){const p=product();$('productName').value=p.name;$('productRelease').value=p.release;$('scenarioInput').value=p.description;$('cveInput').value=p.cve;$('requestFiles').value='';drawFiles();$('requestError').classList.add('hidden')}
function drawFiles(){$('chosenFiles').replaceChildren();product().files.forEach(f=>{const line=document.createElement('div');line.textContent=f.name+' · '+(f.size/1024/1024).toFixed(2)+' MiB（未上傳）';$('chosenFiles').append(line)})}
function snapshot(){const p=product();p.family=family;p.scenario=current;p.supplemented=supplemented}
function switchProduct(id){if(currentView==='intake')saveDraft();snapshot();activeProduct=id;const p=product();family=p.family;current=p.scenario;supplemented=p.supplemented;selectedEvidence=0;render();fillDraft();go(p.mode==='draft'?'intake':'overview')}
function addNew(){if(currentView==='intake')saveDraft();snapshot();const p=newProduct('產品 '+String(products.length+1).padStart(2,'0'));products.push(p);activeProduct=p.id;family=p.family;current='A';supplemented=false;render();fillDraft();go('intake')}
function renderChain(){const p=product(),sample=p.mode==='sample';$('chainRun').textContent=p.runId||'尚未建立';$('requestSummary').textContent=(p.cve?'CVE：'+p.cve+'\n':'CVE：待確認\n')+(p.description||'尚未提供情境，需先釐清產品與漏洞條件。');$('materialSummary').textContent=p.files.length?p.files.map(f=>f.name+'（'+f.size+' bytes，未讀取內容）').join('\n'):sample?'參考工程資料的合成顯示；原始包未載入本頁。':'尚未選擇檔案，可先建立查詢與補件計畫。';$('planNotice').textContent=sample?'目前為獨立合成情境；Query、PC 與結果用於審核畫面，沒有真正執行分析。':'已整理你的輸入，尚未查詢 CVE 知識、讀取檔案或執行 Query。以下是待執行的分析計畫，assessment = null。';$('chainSteps').replaceChildren();['輸入整理','CVE／範圍釐清','Q1–Q5 查證','PC1–PC3 彙整','工程初判','補件與交接'].forEach((name,i)=>{const el=document.createElement('div');el.className='chainstep '+(sample?'done':i===0?'done':i===1?'current':'');const number=document.createElement('span');number.textContent='0'+(i+1);const title=document.createElement('strong');title.textContent=name;const status=document.createElement('span');status.textContent=sample?'合成展示':i===0?'輸入已整理':i===1?'待確認':'等待後端';el.append(number,title,status);$('chainSteps').append(el)});$('queryCards').replaceChildren();queryDefinitions.forEach(q=>{const card=document.createElement('div');card.className='querycard';const meta=document.createElement('div');meta.className='querymeta';const id=document.createElement('span');id.className='id';id.textContent=q.id;const pc=document.createElement('span');pc.className='pill';pc.textContent=q.pc;const status=document.createElement('span');status.className='pill '+(sample&&current==='C'&&!supplemented&&q.evidence>0?'amber':'');status.textContent=sample?(current==='C'&&!supplemented&&q.evidence>0?'示意：仍需补證據':'示意證據摘要'):'待執行';meta.append(id,pc,status);const h=document.createElement('h3');h.textContent=q.name;const text=document.createElement('p');text.textContent=q.purpose;const details=document.createElement('details');const summary=document.createElement('summary');summary.textContent='查看輸入、輸出與判定關聯';const d=document.createElement('p');d.textContent='需要：'+q.inputs+'。預期回傳：'+q.outputs+'。支持 '+q.pc+'；Query 本身不直接產生漏洞結論。';details.append(summary,d);card.append(meta,h,text,details);const action=document.createElement('button');action.className='textbtn';action.style.marginTop='14px';action.textContent=sample?'查看對應證據片段 ↗':'待後端接入，尚無證據';action.disabled=!sample;action.onclick=()=>{showEvidence(q.evidence);go('evidence')};card.append(action);$('queryCards').append(card)})}
function setPlanView(){const p=product();$('resultCard').className='card result amber';$('resultPill').className='pill amber';$('resultPill').textContent='NOT ASSESSED · 尚未分析';$('resultTitle').textContent='分析計畫已建立，等待證據查核';$('resultDesc').textContent='情境描述與檔名不能直接證明產品影響。後端將釐清 CVE 條件，再依序執行五個 Query，彙整 PC1–PC3。';$('metricFiles').textContent=p.files.length+' 份';document.querySelector('#metricFiles + small').textContent='選擇的檔案（未上傳）';$('metricPC').textContent='0 / 3';$('conditions').replaceChildren();['PC1 · 元件與版本','PC2 · 建置與實作','PC3 · 產品關聯與使用路徑'].forEach((label,i)=>{const row=document.createElement('div');row.className='condition';const code=document.createElement('span');code.className='id';code.textContent='PC'+(i+1);const content=document.createElement('div');const title=document.createElement('h3');title.textContent=label;const desc=document.createElement('p');desc.textContent=['等待 Q1_COMPONENT','等待 Q2_BUILD、Q3_IMPLEMENTATION','等待 Q4_BINDING、Q5_PATH'][i];content.append(title,desc);const state=document.createElement('span');state.className='pill amber';state.textContent='未查核';row.append(code,content,state);$('conditions').append(row)});$('package').textContent='輸入草稿／待後端建立資料包';$('binId').textContent='未計算';document.querySelectorAll('#overview .info-row')[2].querySelector('b').textContent='待識別';document.querySelector('#overview .info-row:last-of-type + p').textContent='檔案只保留名稱與大小；沒有解壓、hash 驗證或分析。';$('aiTitle').textContent='先釐清問題，再查證。';$('aiText').textContent='正式版將根據情境和 CVE 條件提出查證方向。此預覽沒有呼叫模型，不會將輸入文字包裝成 AI 分析。';$('aiAction').textContent='查看五個 Query 計畫 ↓';$('aiAction').onclick=()=>$('queriesPanel').scrollIntoView({behavior:'smooth'});$('supplementBtn').disabled=true;$('supplementBtn').textContent='等待後端提供實際缺件清單';$('history').replaceChildren();const msg=document.createElement('p');msg.textContent=p.runId?'已建立本次輸入的模擬計畫 '+p.runId+'；尚無後端分析歷程。':'尚無分析紀錄。';$('history').append(msg);document.querySelector('#supplement .card > p').textContent='未執行分析前，不推測缺件數量。後端回傳缺口後，才補入對應產品與建置的原始材料。';document.querySelector('#supplement .empty p').textContent='需先確認資料包、release、CVE 與現有證據。';$('reportBody').replaceChildren();for(const [label,value] of [['產品',p.name],['Release',p.release||'未指定'],['CVE',p.cve||'待確認'],['工程狀態','NOT_ASSESSED；assessment = null'],['輸入情境',p.description||'未提供'],['後續步驟','Q1 → Q2/Q3 → Q4/Q5 → PC 彙整。所有 Query 待執行。']]){const h=document.createElement('h3');h.style.marginTop='20px';h.textContent=label;const text=document.createElement('p');text.textContent=value;$('reportBody').append(h,text)};$('evidenceRows').replaceChildren();$('excerptTitle').textContent='尚無查詢證據';$('excerptMeta').textContent='等待後端執行 Q1–Q5';$('excerpt').textContent='不會根據情境描述或檔名偽造原始證據。';document.querySelector('#resultCard .eyebrow').textContent=p.cve||'CVE 待確認'}
render=function(){previousRender();const p=product();$('modeBadge').textContent=p.mode==='sample'?'合成參考情境':p.mode==='plan'?'輸入已整理 · 待後端':'新分析草稿';refreshProducts();controls.classList.add('hidden');document.querySelector('.scenarios').classList.toggle('hidden',p.mode!=='sample');renderChain();if(p.mode!=='sample')setPlanView();else $('aiAction').onclick=()=>go(current==='C'&&!supplemented?'supplement':'evidence');document.querySelectorAll('#overview .info-row')[0].querySelector('b').textContent=p.name;document.querySelectorAll('#overview .info-row')[1].querySelector('b').textContent=p.release||'未指定';$('runId').textContent=p.runId||'尚未建立';};
go=function(view){if(view!=='intake'){previousGo(view);$('shell').classList.remove('page-intake')}else{currentView='intake';document.querySelectorAll('.view').forEach(el=>el.classList.toggle('active',el.id==='intake'));document.querySelectorAll('.nav button').forEach(el=>el.classList.toggle('active',el.dataset.view==='intake'));$('crumb').textContent='建立分析';$('title').textContent='從你的問題，開始查核。';$('subtitle').textContent='情境、工程資料、CVE ID，選擇你已掌握的資訊。';$('shell').classList.add('page-intake');fillDraft();window.scrollTo({top:0,behavior:'smooth'})}};
$('requestFiles').onchange=e=>{product().mode='draft';product().runId=null;product().files=[...e.target.files].map(f=>({name:f.name,size:f.size}));drawFiles();render()};
['productName','productRelease','scenarioInput','cveInput'].forEach(id=>$(id).addEventListener('input',saveDraft));
$('requestForm').onsubmit=e=>{e.preventDefault();saveDraft();const p=product();let error='';if(!p.description.trim()&&!p.cve.trim()&&!p.files.length)error='請至少提供情境、檔案或 CVE ID 其中一項。';const ids=p.cve.trim()?p.cve.toUpperCase().split(/[\s,，;；]+/).filter(Boolean):[];if(ids.some(id=>!/^CVE-\d{4}-\d{4,}$/.test(id)))error='CVE 格式應為 CVE-年份-編號；多筆請以逗號或空白分隔。';if(error){$('requestError').textContent=error;$('requestError').classList.remove('hidden');return}p.cve=[...new Set(ids)].join(', ');p.mode='plan';p.startedAt=new Date().toISOString();p.runId='PLAN-'+crypto.randomUUID().slice(0,8);render();go('overview');toast('輸入已整理，分析鏈已建立；尚未執行後端分析。')};
$('exampleInput').onclick=()=>{const p=product();p.description='這台閘道器使用 OpenSSL 處理 TLS。掃描报告提到 Heartbleed，我想確認出貨版本是否編入 heartbeat、產品入口是否使用相關路徑，以及需要補哪些資料。';p.cve='CVE-2014-0160';fillDraft()};
$('loadSample').onclick=()=>{saveDraft();snapshot();const f=$('sampleFamily').value;const p=newProduct(families[f].label+' · 參考產品');p.family=f;p.mode='sample';p.cve=families[f].cve.split(' · ')[0];p.description='參考工程資料的合成結果，用於審核完整查核與補件流程。';p.runId='SAMPLE-'+crypto.randomUUID().slice(0,8);products.push(p);activeProduct=p.id;family=f;current='A';supplemented=false;render();go('overview')};
$('productSelect').onchange=e=>switchProduct(e.target.value);$('addProduct').onclick=addNew;$('editRequest').onclick=()=>go('intake');
$('viewAfter').onclick=()=>{if(product().mode==='sample')current='C';render();go('overview')};
const oldReset=$('reset').onclick;$('reset').onclick=()=>{if(product().mode==='sample')oldReset();else go('intake')};
document.querySelectorAll('.nav button').forEach(b=>b.onclick=()=>go(b.dataset.view));
render();fillDraft();go('intake');
